#!/bin/sh
set -e

KIOSK_URL="${KIOSK_URL:-https://akior.local/menu}"

# Keep display awake
xset -dpms || true
xset s off || true
xset s noblank || true

# Start minimal window manager
openbox-session &
sleep 1

launch_chromium() {
    chromium-browser \
        --kiosk \
        --incognito \
        --start-fullscreen \
        --no-first-run \
        --noerrdialogs \
        --disable-infobars \
        --disable-session-crashed-bubble \
        --disable-restore-session-state \
        --disable-features=TranslateUI \
        --disable-pinch \
        --overscroll-history-navigation=0 \
        --ignore-certificate-errors \
        --user-data-dir=/home/akior-kiosk/.chromium-kiosk \
        "$KIOSK_URL"
}

while true; do
    launch_chromium || true
    sleep 2
done
